name: home_info
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  auto_route: 7.8.4
  get_it: 7.6.7
  flutter_bloc: 8.1.3
  shared_preferences: 2.2.2
  equatable: 2.0.5
  sqflite: 2.3.2
  path: 1.9.0
  uuid: 4.3.3
  flutter_slidable: 3.0.1
  flutter_local_notifications: 16.3.2
  timezone: 0.9.2
  share_plus: 7.2.2
  fl_chart: 0.66.2
  path_provider: 2.1.3
  flutter_file_dialog: 3.0.2
  file_picker: 8.0.6
  package_info_plus: 8.0.1
  flutter_email_sender: 6.0.3
  in_app_review: 2.0.9



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner:

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/theme_images/
    - assets/images/services_images/
    - assets/images/other_images/


  fonts:
    - family: Montserrat-Bold_700
      fonts:
        - asset: assets/fonts/Montserrat-Bold_700.ttf
    - family: Montserrat-Medium_500
      fonts:
        - asset: assets/fonts/Montserrat-Medium_500.ttf
